artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Aamil-Abdulla/text-summarizer-project-zip/raw/refs/heads/main/samsumdata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.json
  ALL_REQUIRED_FILES:
    - samsum-train.csv
    - samsum-validation.csv
    - samsum-test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  train_path: artifacts/data_ingestion/samsum-train.csv
  validation_path: artifacts/data_ingestion/samsum-validation.csv
  test_path: artifacts/data_ingestion/samsum-test.csv
  tokenizer_name: t5-small

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_ckpt: t5-small
  logging_dir: artifacts/model_trainer/logs
  logging_steps: 10
  evaluation_strategy: "steps"
  save_strategy: "epoch"
  save_total_limit: 2
  fp16: false
  push_to_hub: false
  hub_model_id: ""
  hub_token: ""



model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer/t5-summarizer
  tokenizer_path: artifacts/model_trainer/tokenizer
  data_path: artifacts/data_ingestion/samsum-test.csv
  metric_file_name: artifacts/model_evaluation/metric.csv
  column_text: dialogue
  column_summary: summary
